import os
import json
import shutil
import yaml
import tempfile
from functools import partial
from pathlib import Path
import numpy as np

from ultralytics import YOLO
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

from dagri.interfaces import BaselineConfig, DatasetProperties, EvaluationResults, PredictionResult, BoundingBox
from dagri.baseline.utils import create_coco_gt_json_from_yolo
from dagri.weighting import WeightedDetectionTrainer


class YoloUltralyticsModel:
    """
    A wrapper class for the YOLO model using the Ultralytics library. This class will handle training, evaluation, and inference using the YOLO model.
    """
    def __init__(self, baseline_config: BaselineConfig):
        # Initialize config
        self.train_config = baseline_config.training_config
        self.evaluation_config = baseline_config.evaluation_config
        # Initialize model
        self.model = YOLO(baseline_config.pretrained_weights_path)
    
    def custom_train(
        self,
        dataset_properties: DatasetProperties,
        output_dir_for_best_weights: str,
        image_score_map: dict[str, float] | None = None,
        weight_function: str = "linear",
        weight_gamma: float = 1.0,
        normalize_scores: bool = True,
    ) -> str:
        """
        Train YOLO model and save best weights to output directory.
        
        Args:
            dataset_properties: Properties of the dataset to use for training
            output_dir_for_best_weights: Directory to save best.pt

        Returns:
            Path to the copied best.pt file.
        """
        os.makedirs(output_dir_for_best_weights, exist_ok=True)
        
        # Create data.yaml from dataset properties
        data_path = self._create_data_yaml(dataset_properties, output_dir_for_best_weights)
        
        output_dir_for_best_weights = os.path.abspath(output_dir_for_best_weights)

        train_kwargs = {
            "data": data_path,
            "epochs": self.train_config.epochs,
            "batch": self.train_config.batch_size,
            "imgsz": self.train_config.input_size,
            "lr0": self.train_config.learning_rate,
            "seed": self.train_config.seed,
            "patience": self.train_config.early_stopping_patience,
            "deterministic": True,
            "save": True,
            "save_period": -1,
            "plots": False,
            "verbose": False,
            "project": output_dir_for_best_weights,
            "name": "train",
            "exist_ok": True,
        }

        # Ultralytics expects `augment` to be bool. Pass configured augmentation values
        # as individual training arguments (hsv_h, degrees, fliplr, etc.).
        aug_cfg = self.train_config.traditional_augmentation_config or {}
        if isinstance(aug_cfg, dict):
            train_kwargs.update(aug_cfg)

        trainer_factory = None
        if image_score_map:
            trainer_factory = partial(
                WeightedDetectionTrainer,
                weighted_config={
                    "enabled": True,
                    "image_score_map": image_score_map,
                    "weight_function": weight_function,
                    "weight_gamma": weight_gamma,
                    "normalize_scores": normalize_scores,
                },
            )

        if trainer_factory is None:
            self.model.train(**train_kwargs)
        else:
            self.model.train(trainer=trainer_factory, **train_kwargs)

        trainer_best = getattr(getattr(self.model, "trainer", None), "best", None)
        weight_src = str(trainer_best) if trainer_best else ""
        if not weight_src or not os.path.exists(weight_src):
            weight_src = os.path.join(output_dir_for_best_weights, "train", "weights", "best.pt")
        weight_dst = os.path.join(output_dir_for_best_weights, "best.pt")
        if not os.path.exists(weight_src):
            raise FileNotFoundError(f"Best weight not found after training: {weight_src}")

        shutil.copy(weight_src, weight_dst)
        return weight_dst
    
    def custom_evaluate_on_test_set(self, best_weight_path: str, dataset: DatasetProperties) -> EvaluationResults:
        """
        Evaluate the trained model on test set and return typed COCO metrics.
        
        Args:
            best_weight_path: Path to best model weights generated by custom_train
        """
        if not os.path.exists(best_weight_path):
            raise FileNotFoundError(f"Best weight file not found: {best_weight_path}")

        dataset_properties = dataset
        test_images_dir = dataset_properties.test_images_dir
        test_labels_dir = dataset_properties.test_labels_dir

        if not test_images_dir or not test_labels_dir:
            raise ValueError("dataset_properties must include test_images_dir and test_labels_dir")

        with tempfile.TemporaryDirectory(prefix="eval_test_") as tmp_dir:
            data_path = self._create_data_yaml(dataset_properties, tmp_dir)
            coco_gt_json = os.path.join(tmp_dir, "test_coco_gt.json")

            create_coco_gt_json_from_yolo(
                images_dir=test_images_dir,
                output_json_path=coco_gt_json,
                labels_dir=test_labels_dir,
                class_names=dataset_properties.class_names,
            )

            eval_model = YOLO(best_weight_path)

            val_kwargs = {
                "data": data_path,
                "split": "test",
                "save_json": True,
                "project": tmp_dir,
                "name": "evaluation",
                "exist_ok": True,
                "plots": False,
                "verbose": False,
            }

            if self.evaluation_config.image_size is not None:
                val_kwargs["imgsz"] = self.evaluation_config.image_size
            if self.evaluation_config.confidence_threshold is not None:
                val_kwargs["conf"] = self.evaluation_config.confidence_threshold
            if self.evaluation_config.iou_threshold is not None:
                val_kwargs["iou"] = self.evaluation_config.iou_threshold
            if self.evaluation_config.max_detections is not None:
                val_kwargs["max_det"] = self.evaluation_config.max_detections

            val_results = eval_model.val(**val_kwargs)

            candidate_dirs = [os.path.join(tmp_dir, "evaluation")]
            for maybe_dir in [
                getattr(val_results, "save_dir", None),
                getattr(getattr(eval_model, "validator", None), "save_dir", None),
                getattr(getattr(eval_model, "trainer", None), "save_dir", None),
            ]:
                if maybe_dir:
                    candidate_dirs.append(str(maybe_dir))

            pred_json_path = ""
            for candidate_dir in candidate_dirs:
                candidate_json = os.path.join(candidate_dir, "predictions.json")
                if os.path.exists(candidate_json):
                    pred_json_path = candidate_json
                    break

            if not os.path.exists(pred_json_path):
                raise FileNotFoundError(
                    "Predictions JSON not  0.04created. Checked: " + ", ".join(candidate_dirs)
                )

            coco_gt = COCO(coco_gt_json)
            coco_dt = coco_gt.loadRes(pred_json_path)
            coco_eval = COCOeval(coco_gt, coco_dt, iouType="bbox")
            coco_eval.evaluate()
            coco_eval.accumulate()
            coco_eval.summarize()

            size_band_stats = self._evaluate_ap_by_pixel_size(coco_gt, coco_dt)
            print("Custom AP by object size (equivalent square side length in pixels)")
            print(f"  AP very small (<20px):   {size_band_stats['AP_very_small']:.4f}")
            print(f"  AP small (20-32px):      {size_band_stats['AP_small_20_32']:.4f}")
            print(f"  AP medium (>32px):       {size_band_stats['AP_medium_gt_32']:.4f}")

            stats = coco_eval.stats

            return EvaluationResults(
                COCO_AP=float(stats[0]),
                COCO_AP50=float(stats[1]),
                COCO_AP75=float(stats[2]),
                AP_small=float(stats[3]),
                AP_medium=float(stats[4]),
                AP_large=float(stats[5]),
                AP_very_small=float(size_band_stats["AP_very_small"]),
                AP_small_20_32=float(size_band_stats["AP_small_20_32"]),
                AP_medium_gt_32=float(size_band_stats["AP_medium_gt_32"]),
            )

    def custom_evaluate(self, best_weight_path: str, dataset: DatasetProperties) -> EvaluationResults:
        """Backward-compatible alias for test-set evaluation."""
        return self.custom_evaluate_on_test_set(best_weight_path, dataset)

    @staticmethod
    def _compute_mean_ap_for_area_label(coco_eval: COCOeval, area_label: str) -> float:
        """Compute mean AP for a named area range from an accumulated COCOeval object."""
        area_labels = list(getattr(coco_eval.params, "areaRngLbl", []))
        if area_label not in area_labels:
            raise ValueError(f"Area label not found in COCOeval params: {area_label}")

        area_idx = area_labels.index(area_label)
        max_det_idx = len(coco_eval.params.maxDets) - 1

        precision = np.asarray(coco_eval.eval["precision"], dtype=float)
        precision = precision[:, :, :, area_idx, max_det_idx]
        precision = precision[precision > -1]
        if precision.size == 0:
            return float("nan")
        return float(np.mean(precision))

    def _evaluate_ap_by_pixel_size(self, coco_gt: COCO, coco_dt) -> dict[str, float]:
        """
        Compute AP over custom pixel-size buckets.

        The buckets are defined on the equivalent square side length, i.e. area thresholds
        of 20^2 and 32^2 pixels for very small / small / medium.
        """
        custom_eval = COCOeval(coco_gt, coco_dt, iouType="bbox")
        custom_eval.params.areaRng = [
            [0.0, 1e10],
            [0.0, 20.0**2],
            [20.0**2, 32.0**2],
            [32.0**2, 1e10],
        ]
        custom_eval.params.areaRngLbl = ["all", "very_small", "small_20_32", "medium_gt_32"]
        custom_eval.evaluate()
        custom_eval.accumulate()

        return {
            "AP_very_small": self._compute_mean_ap_for_area_label(custom_eval, "very_small"),
            "AP_small_20_32": self._compute_mean_ap_for_area_label(custom_eval, "small_20_32"),
            "AP_medium_gt_32": self._compute_mean_ap_for_area_label(custom_eval, "medium_gt_32"),
        }

    def _create_data_yaml(self, dataset_properties: DatasetProperties, output_dir: str) -> str:
        """
        Create a YOLO data.yaml from dataset properties.
        
        Args:
            output_dir: Directory to save the generated data.yaml
            
        Returns:
            Path to the generated data.yaml file
        """
        dataset_properties = dataset_properties
        # Get properties
        root_dir = dataset_properties.root_dir
        class_names = dataset_properties.class_names or ["object"]
        
        # Create data.yaml content using paths from dataset properties
        data_yaml = {
            "path": root_dir,
            "train": dataset_properties.train_images_dir,
            "val": dataset_properties.val_images_dir,
            "test": dataset_properties.test_images_dir,
            "nc": dataset_properties.num_classes or len(class_names),
            "names": {i: name for i, name in enumerate(class_names)}
        }
        
        # Write to yaml file
        yaml_path = os.path.join(output_dir, "data.yaml")
        os.makedirs(output_dir, exist_ok=True)
        with open(yaml_path, "w") as f:
            yaml.dump(data_yaml, f, default_flow_style=False)
        
        return yaml_path
    
    def custom_predict(self, model_weight: str, image_dir: str, conf: float, iou: float, max_det: int) -> list[PredictionResult]:
        """
        Run inference on a directory of images and return prediction results.
        
        Args:
            model_weight: Path to the pre-trained model weights
            image_dir: Path to directory containing input images
            conf: Confidence threshold for predictions
            iou: IoU threshold for non-maximum suppression
            max_det: Maximum number of detections per image
            
        Returns:
            List of PredictionResult objects, one for each image
        """
        model = YOLO(model_weight)
        predict_result = model.predict(source=image_dir, save=False, conf=conf, iou=iou, max_det=max_det)
        
        prediction_results = []
        
        for result in predict_result:
            # Get normalized boxes (0-1), classes, and confidences
            boxes_normalized = result.boxes.xywhn.cpu().numpy()  # [N, 4]
            classes = result.boxes.cls.cpu().numpy()              # [N]
            confidences = result.boxes.conf.cpu().numpy()         # [N]
            
            # Create BoundingBox objects
            predicted_boxes = [
                BoundingBox(x_center=float(box[0]), y_center=float(box[1]), width=float(box[2]), height=float(box[3]))
                for box in boxes_normalized
            ]
            
            # Create PredictionResult
            pred_result = PredictionResult(
                image_path=result.path,
                classes=classes.tolist(),
                confidences=confidences.tolist(),
                predicted_boxes=predicted_boxes
            )
            prediction_results.append(pred_result)
        
        return prediction_results
        

    def get_optimal_conf_threshold_for_scoring(
        self,
        dataset_properties: DatasetProperties,
        model_weight: str,
    ) -> float:
        """
        Run validation once and select confidence threshold from the native F1 curve.

        Uses val_metrics.box confidence/F1 arrays computed by Ultralytics and picks the
        confidence value at maximum F1.

        """
        if not os.path.exists(model_weight):
            raise FileNotFoundError(f"Model weight file not found: {model_weight}")
        if not dataset_properties.val_images_dir or not dataset_properties.val_labels_dir:
            raise ValueError("dataset_properties must include val_images_dir and val_labels_dir")

        model = YOLO(model_weight)

        with tempfile.TemporaryDirectory(prefix="conf_threshold_search_") as tmp_dir:
            data_path = self._create_data_yaml(dataset_properties, tmp_dir)
            # Use a low confidence once to preserve predictions needed for full PR/F1 curves.
            val_kwargs = {
                "data": data_path,
                "split": "val",
                "conf": 0.001,
                "save_json": False,
                "plots": False,
                "verbose": False,
            }

            if self.evaluation_config.image_size is not None:
                val_kwargs["imgsz"] = self.evaluation_config.image_size
            if self.evaluation_config.iou_threshold is not None:
                val_kwargs["iou"] = self.evaluation_config.iou_threshold
            if self.evaluation_config.max_detections is not None:
                val_kwargs["max_det"] = self.evaluation_config.max_detections

            val_metrics = model.val(**val_kwargs)

        box = getattr(val_metrics, "box", None)
        if box is None:
            raise RuntimeError("Validation result has no 'box' metrics to extract F1 curve")

        # Ultralytics stores confidence x-axis and F1 curve arrays on the box metric.
        conf_curve = getattr(box, "px", None)
        f1_curve = getattr(box, "f1_curve", None)
        if conf_curve is None or f1_curve is None:
            curves = getattr(box, "curves_results", None)
            if isinstance(curves, (list, tuple)) and len(curves) >= 3:
                conf_curve = curves[0]
                f1_curve = curves[2]

        if conf_curve is None or f1_curve is None:
            raise RuntimeError("Could not extract confidence/F1 curve arrays from val_metrics.box")

        conf_arr = np.asarray(conf_curve, dtype=float).reshape(-1)
        f1_arr = np.asarray(f1_curve, dtype=float)
        if f1_arr.ndim > 1:
            # Multi-class: aggregate to one global curve.
            f1_arr = np.nanmean(f1_arr, axis=0)
        f1_arr = f1_arr.reshape(-1)

        if conf_arr.size == 0 or f1_arr.size == 0:
            raise RuntimeError("Empty confidence/F1 curve arrays in validation metrics")

        if conf_arr.size != f1_arr.size:
            min_len = min(conf_arr.size, f1_arr.size)
            conf_arr = conf_arr[:min_len]
            f1_arr = f1_arr[:min_len]

        best_idx = int(np.nanargmax(f1_arr))
        best_conf = float(conf_arr[best_idx])
        return float(round(best_conf, 6))
