import os
import json
import shutil
import yaml
from pathlib import Path

from ultralytics import YOLO
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

from dagri.interfaces import BaselineConfig, DatasetProperties
from dagri.baseline.utils import create_coco_gt_json_from_yolo


class YoloUltralyticsModel:
    """
    A wrapper class for the YOLO model using the Ultralytics library. This class will handle training, evaluation, and inference using the YOLO model.
    """
    def __init__(self, baseline_config: BaselineConfig):
        # Initialize config
        self.train_config = baseline_config.training_config
        self.evaluation_config = baseline_config.evaluation_config
        # Initialize model
        self.model = YOLO(baseline_config.pretrained_weights_path)
    
    def custom_train(self, dataset_properties: DatasetProperties, output_dir_for_best_weights: str) -> str:
        """
        Train YOLO model and save best weights to output directory.
        
        Args:
            dataset_properties: Properties of the dataset to use for training
            output_dir_for_best_weights: Directory to save best.pt

        Returns:
            Path to the copied best.pt file.
        """
        os.makedirs(output_dir_for_best_weights, exist_ok=True)
        
        # Create data.yaml from dataset properties
        data_path = self._create_data_yaml(dataset_properties, output_dir_for_best_weights)
        
        output_dir_for_best_weights = os.path.abspath(output_dir_for_best_weights)

        train_kwargs = {
            "data": data_path,
            "epochs": self.train_config.epochs,
            "batch": self.train_config.batch_size,
            "imgsz": self.train_config.input_size,
            "lr0": self.train_config.learning_rate,
            "seed": self.train_config.seed,
            "patience": self.train_config.early_stopping_patience,
            "deterministic": True,
            "save": True,
            "save_period": -1,
            "plots": False,
            "verbose": False,
            "project": output_dir_for_best_weights,
            "name": "train",
            "exist_ok": True,
        }

        # Ultralytics expects `augment` to be bool. Pass configured augmentation values
        # as individual training arguments (hsv_h, degrees, fliplr, etc.).
        aug_cfg = self.train_config.traditional_augmentation_config or {}
        if isinstance(aug_cfg, dict):
            train_kwargs.update(aug_cfg)
       
        
        self.model.train(**train_kwargs)

        trainer_best = getattr(getattr(self.model, "trainer", None), "best", None)
        weight_src = str(trainer_best) if trainer_best else ""
        if not weight_src or not os.path.exists(weight_src):
            weight_src = os.path.join(output_dir_for_best_weights, "train", "weights", "best.pt")
        weight_dst = os.path.join(output_dir_for_best_weights, "best.pt")
        if not os.path.exists(weight_src):
            raise FileNotFoundError(f"Best weight not found after training: {weight_src}")

        shutil.copy(weight_src, weight_dst)
        return weight_dst
    
    def custom_evaluate(self, best_weight_path: str, dataset: DatasetProperties, output_dir: str) -> dict:
        """
        Evaluate the trained model on test set with COCO metrics.
        
        Args:
            best_weight_path: Path to best model weights generated by custom_train
            output_dir: Directory to save evaluation results
        """
        if not os.path.exists(best_weight_path):
            raise FileNotFoundError(f"Best weight file not found: {best_weight_path}")
        
        output_dir = os.path.abspath(output_dir)
        os.makedirs(output_dir, exist_ok=True)

        dataset_properties = dataset

        data_path = self._create_data_yaml(dataset_properties, output_dir)
        test_images_dir = dataset_properties.test_images_dir
        test_labels_dir = dataset_properties.test_labels_dir
        coco_gt_json = os.path.join(output_dir, "test_coco_gt.json")

        if not test_images_dir or not test_labels_dir:
            raise ValueError("dataset_properties must include test_images_dir and test_labels_dir")

        create_coco_gt_json_from_yolo(
            images_dir=test_images_dir,
            output_json_path=coco_gt_json,
            labels_dir=test_labels_dir,
            class_names=dataset_properties.class_names,
        )

        eval_model = YOLO(best_weight_path)
        
        val_kwargs = {
            "data": data_path,
            "split": "test",
            "save_json": True,
            "project": output_dir,
            "name": "evaluation",
            "exist_ok": True,
        }
        
        if self.evaluation_config.image_size is not None:
            val_kwargs["imgsz"] = self.evaluation_config.image_size
        if self.evaluation_config.confidence_threshold is not None:
            val_kwargs["conf"] = self.evaluation_config.confidence_threshold
        if self.evaluation_config.iou_threshold is not None:
            val_kwargs["iou"] = self.evaluation_config.iou_threshold
        if self.evaluation_config.max_detections is not None:
            val_kwargs["max_det"] = self.evaluation_config.max_detections

        val_results = eval_model.val(**val_kwargs)

        candidate_dirs = [
            os.path.join(output_dir, "evaluation"),
        ]
        for maybe_dir in [
            getattr(val_results, "save_dir", None),
            getattr(getattr(eval_model, "validator", None), "save_dir", None),
            getattr(getattr(eval_model, "trainer", None), "save_dir", None),
        ]:
            if maybe_dir:
                candidate_dirs.append(str(maybe_dir))

        pred_json_path = ""
        for candidate_dir in candidate_dirs:
            candidate_json = os.path.join(candidate_dir, "predictions.json")
            if os.path.exists(candidate_json):
                pred_json_path = candidate_json
                break

        if not os.path.exists(pred_json_path):
            raise FileNotFoundError(
                "Predictions JSON not created. Checked: " + ", ".join(candidate_dirs)
            )

        coco_gt = COCO(coco_gt_json)
        coco_dt = coco_gt.loadRes(pred_json_path)
        coco_eval = COCOeval(coco_gt, coco_dt, iouType="bbox")
        coco_eval.evaluate()
        coco_eval.accumulate()
        coco_eval.summarize()

        stats = coco_eval.stats

        results = {
            "COCO_AP": float(stats[0]),
            "COCO_AP50": float(stats[1]),
            "COCO_AP75": float(stats[2]),
            "AP_small": float(stats[3]),
            "AP_medium": float(stats[4]),
            "AP_large": float(stats[5]),
        }

        results_path = os.path.join(output_dir, "evaluation_results.json")
        with open(results_path, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=2)

        return results

    def _create_data_yaml(self, dataset_properties: DatasetProperties, output_dir: str) -> str:
        """
        Create a YOLO data.yaml from dataset properties.
        
        Args:
            output_dir: Directory to save the generated data.yaml
            
        Returns:
            Path to the generated data.yaml file
        """
        dataset_properties = dataset_properties
        # Get properties
        root_dir = dataset_properties.root_dir
        class_names = dataset_properties.class_names or ["object"]
        
        # Create data.yaml content using paths from dataset properties
        data_yaml = {
            "path": root_dir,
            "train": dataset_properties.train_images_dir,
            "val": dataset_properties.val_images_dir,
            "test": dataset_properties.test_images_dir,
            "nc": dataset_properties.num_classes or len(class_names),
            "names": {i: name for i, name in enumerate(class_names)}
        }
        
        # Write to yaml file
        yaml_path = os.path.join(output_dir, "data.yaml")
        os.makedirs(output_dir, exist_ok=True)
        with open(yaml_path, "w") as f:
            yaml.dump(data_yaml, f, default_flow_style=False)
        
        return yaml_path
    
    def custom_predict(self, model_weight: str, image_dir: str, output_dir: str, conf: float, iou: float, max_det: int) -> None:
        """
        Run inference on a directory of images.
        
        Args:
            model_weight: Path to the pre-trained model weights
            image_dir: Path to directory containing input images
            output_dir: Path to directory where predictions will be saved
            conf: Confidence threshold for predictions
            iou: IoU threshold for non-maximum suppression
            max_det: Maximum number of detections per image
        """
        output_dir = Path(output_dir)
        model = YOLO(model_weight)
        predict_result = model.predict(source=image_dir, save=False, conf=conf, iou=iou, max_det=max_det)
        # Save predictions to output directory
        os.makedirs(output_dir, exist_ok=True)

        for result in predict_result:
            # Get image name without extension
            image_name = Path(result.path).stem
            label_file = output_dir / f"{image_name}.txt"
            
            # Get normalized boxes (0-1), classes, and confidences
            boxes_normalized = result.boxes.xywhn.cpu().numpy()  # [N, 4]
            classes = result.boxes.cls.cpu().numpy()              # [N]
            confidences = result.boxes.conf.cpu().numpy()         # [N]
            
            # Write YOLO format: class x_center y_center width height confidence
            with open(label_file, 'w') as f:
                for i, box in enumerate(boxes_normalized):
                    cls = int(classes[i])
                    x_c, y_c, w, h = box
                    conf = confidences[i]
                    f.write(f"{cls} {x_c:.6f} {y_c:.6f} {w:.6f} {h:.6f} {conf:.6f}\n")
 
        print(f"Predictions saved to: {output_dir}")
